import type { Datum } from '@/utils/data';

export const mockData: Datum[] = [
  {
    tempmin: 3.1,
    tempmax: 11.9,
    datetime: '2022-01-01',
    uvindex: 3,
    precipprob: 100,
    preciptype: 'rain',
    cloudcover: 62.8,
    windspeed: 11.9,
    winddir: 313.8,
    description:
      'Partly cloudy throughout the day with rain in the morning and afternoon.',
  },
  {
    tempmin: 5.7,
    tempmax: 14,
    datetime: '2022-01-02',
    uvindex: 4,
    precipprob: 0,
    preciptype: undefined,
    cloudcover: 46.9,
    windspeed: 12.8,
    winddir: 163.4,
    description: 'Partly cloudy throughout the day.',
  },
  {
    tempmin: 4.8,
    tempmax: 12.1,
    datetime: '2022-01-03',
    uvindex: 4,
    precipprob: 0,
    preciptype: undefined,
    cloudcover: 37.5,
    windspeed: 12,
    winddir: 225.2,
    description: 'Partly cloudy throughout the day.',
  },
  {
    tempmin: 2.5,
    tempmax: 13.8,
    datetime: '2022-01-04',
    uvindex: 3,
    precipprob: 0,
    preciptype: undefined,
    cloudcover: 46.4,
    windspeed: 14.9,
    winddir: 133.6,
    description: 'Becoming cloudy in the afternoon.',
  },
  {
    tempmin: 7.3,
    tempmax: 16.5,
    datetime: '2022-01-05',
    uvindex: 4,
    precipprob: 0,
    preciptype: undefined,
    cloudcover: 55.1,
    windspeed: 16.5,
    winddir: 87.5,
    description: 'Partly cloudy throughout the day.',
  },
  {
    tempmin: 2,
    tempmax: 5.8,
    datetime: '2022-01-06',
    uvindex: 1,
    precipprob: 100,
    preciptype: 'rain',
    cloudcover: 88.6,
    windspeed: 13,
    winddir: 290.5,
    description:
      'Partly cloudy throughout the day with rain in the morning and afternoon.',
  },
  {
    tempmin: -1,
    tempmax: 3.6,
    datetime: '2022-01-07',
    uvindex: 3,
    precipprob: 0,
    preciptype: undefined,
    cloudcover: 78.7,
    windspeed: 10.8,
    winddir: 328.8,
    description: 'Partly cloudy throughout the day.',
  },
  {
    tempmin: -0.2,
    tempmax: 1.9,
    datetime: '2022-01-08',
    uvindex: 2,
    precipprob: 100,
    preciptype: 'sleet',
    cloudcover: 95.2,
    windspeed: 11.3,
    winddir: 1.1,
    description: 'Cloudy skies throughout the day with rain or snow.',
  },
  {
    tempmin: -1.3,
    tempmax: 1,
    datetime: '2022-01-09',
    uvindex: 4,
    precipprob: 100,
    preciptype: 'sleet',
    cloudcover: 90.4,
    windspeed: 9,
    winddir: 342.6,
    description:
      'Cloudy skies throughout the day with rain or snow clearing later.',
  },
  {
    tempmin: -1.8,
    tempmax: -0.2,
    datetime: '2022-01-10',
    uvindex: 1,
    precipprob: 100,
    preciptype: 'sleet',
    cloudcover: 98.3,
    windspeed: 13.7,
    winddir: 332.9,
    description:
      'Cloudy skies throughout the day with a chance of rain or snow throughout the day.',
  },
  {
    tempmin: -1.7,
    tempmax: -0.8,
    datetime: '2022-01-11',
    uvindex: 2,
    precipprob: 100,
    preciptype: 'sleet',
    cloudcover: 98.5,
    windspeed: 11.6,
    winddir: 294.6,
    description:
      'Cloudy skies throughout the day with a chance of rain or snow throughout the day.',
  },
  {
    tempmin: -6,
    tempmax: -1.2,
    datetime: '2022-01-12',
    uvindex: 2,
    precipprob: 100,
    preciptype: 'sleet',
    cloudcover: 84.3,
    windspeed: 12.7,
    winddir: 308.4,
    description:
      'Partly cloudy throughout the day with early morning snow or rain.',
  },
  /*   {
    tempmin: -8.5,
    tempmax: -0.9,
    datetime: '2022-01-13',
    uvindex: 3,
    precipprob: 100,
    preciptype: 'snow',
    cloudcover: 54.5,
    windspeed: 10.6,
    winddir: 289.1,
    description: 'Partly cloudy throughout the day with morning snow.',
  },
  {
    tempmin: -6.7,
    tempmax: 3.8,
    datetime: '2022-01-14',
    uvindex: 3,
    precipprob: 100,
    preciptype: 'snow',
    cloudcover: 40,
    windspeed: 10.7,
    winddir: 283,
    description: 'Partly cloudy throughout the day with morning snow.',
  } */
  ,
];
