// AUTOGENERATED: DO NOT MODIFY
import type { Domains } from './utils.mts';

export const domains: Domains = {
  tempmin: [-12.4, 25.8],
  tempmax: [-4.1, 38.6],
  precipprob: [0, 100],
  windspeed: [5.9, 44.7],
  cloudcover: [0, 100],
};
