// AUTOGENERATED: DO NOT MODIFY
import type { Domains } from './utils.js';

export const domains: Domains = {
  tempmin: [-12.4, 22.9],
  tempmax: [-3, 38.6],
  precipprob: [0, 100],
  windspeed: [5.9, 44.7],
};
